import "./scripts/muscules/musculesRender";
import "./scripts/favoritesClick";
import "./scripts/muscules/renderCarts";
// import "./scripts/filters";
import "./scripts/searhCart";
import "./scripts/burgerMenu";
import "./scripts/quote/quote";
import "./scripts/subscription";
import "./scripts/rating/reviewForm";
import "./scripts/rating/reviewClose";
